name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Run `openapi:validate` on file with refs (take 1)
        uses: readmeio/rdme@v8
        continue-on-error: true
        with:
          rdme: openapi:validate __tests__/__fixtures__/ref-oas/petstore.json

      - name: Run `openapi:validate` on file with refs (take 2)
        uses: readmeio/rdme@v8
        continue-on-error: true
        with:
          rdme: openapi:validate __tests__/__fixtures__/ref-oas/petstore.json --workingDirectory ${{ github.workspace }}

      - name: Run `openapi:validate` on file with relative refs (take 1)
        uses: readmeio/rdme@v8
        continue-on-error: true
        with:
          rdme: openapi:validate __tests__/__fixtures__/relative-ref-oas/petstore.json --workingDirectory __tests__/__fixtures__/relative-ref-oas

      - name: Run `openapi:validate` on file with relative refs (take 2)
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate __tests__/__fixtures__/relative-ref-oas/petstore.json --workingDirectory ${{ github.workspace }}/__tests__/__fixtures__/relative-ref-oas
